name: Hydrax Video Worker

on:
  repository_dispatch:
    types: [trigger-download-upload]

jobs:
  process-video:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Execute Task
      env:
        HYDRAX_API_KEY: ${{ secrets.HYDRAX_API_KEY }}
        VPS_CALLBACK_URL: ${{ secrets.VPS_CALLBACK_URL1 }}
        SECRET_AUTH_KEY: ${{ secrets.SECRET_AUTH_KEY }}
        DOWNLOAD_URL: ${{ github.event.client_payload.download_url }}
        VIDEO_ID: ${{ github.event.client_payload.video_id }}
        PLATFORM: ${{ github.event.client_payload.platform }}
      run: |
        RANDOM_NAME=$(date +%s%N | md5sum | awk '{print toupper($1)}').mp4
        
        curl -L "$DOWNLOAD_URL" -o "$RANDOM_NAME"
        
        RESPONSE=$(curl -S -s -X POST -F "file=@$RANDOM_NAME" "https://up.abyss.to/$HYDRAX_API_KEY")
        HYDRAX_TAG=$(echo "$RESPONSE" | grep -o '"slug":"[^"]*' | head -n 1 | cut -d'"' -f4)
        
        if [ ! -z "$HYDRAX_TAG" ] && [ "$HYDRAX_TAG" != "null" ]; then
          curl -s -X POST \
            -H "Content-Type: application/json" \
            -d "{\"video_id\":\"$VIDEO_ID\", \"platform\":\"$PLATFORM\", \"hydrax_tag\":\"$HYDRAX_TAG\"}" \
            "${VPS_CALLBACK_URL1}?secret=${SECRET_AUTH_KEY}"
            
          echo "RESULT_DATA|Platform:$PLATFORM|VideoID:$VIDEO_ID|Tag:$HYDRAX_TAG"
        else
          rm -f "$RANDOM_NAME"
          exit 1
        fi

        rm -f "$RANDOM_NAME"
